services:
  redis:
    image: redis:8
    ports:
      - 6379:6379
    command: >
      --requirepass supersecure
    volumes:
     - redisearch-data:/data

  redisinsight: # optional for debug and visualize redis data
    image: redis/redisinsight:latest
    ports:
      - 5540:5540 # redis insight: to connect use "redis://default:supersecure@redis:6379"
    depends_on:
      - "redis"

volumes:
  redisearch-data:
