services:
  solr:
    image: "solr:10"
    ports:
     - "8983:8983"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8983/solr/admin/info/system?wt=json || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - solr-data:/var/solr

volumes:
  solr-data:
